# Generated by Django 4.2.5 on 2025-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course Registration', 'verbose_name_plural': 'Course Registrations'},
        ),
        migrations.RemoveField(
            model_name='courseregistration',
            name='course',
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='registrations', to='main.course'),
        ),
    ]
