# Generated by Django 4.2.5 on 2025-07-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_courseregistration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Class Time',
                'verbose_name_plural': 'Class Times',
                'db_table': 'class_time_option',
            },
        ),
        migrations.CreateModel(
            name='StudyMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Study Mode',
                'verbose_name_plural': 'Study Modes',
                'db_table': 'study_mode',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'db_table': 'university',
            },
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='apply_for_merit_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='current_city_or_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='current_education_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='heard_about_us',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='telegram_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='top_goal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='wants_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='ideal_class_times',
            field=models.ManyToManyField(blank=True, to='main.classtimeoption'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='intended_universities',
            field=models.ManyToManyField(blank=True, to='main.university'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='preferred_study_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.studymode'),
        ),
    ]
